Controllers/AuthController.cs
using Client.Authentication;
using Client.Models;
using Core.Entities;
using Core.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.Google;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class AuthController : Controller
    {
        private readonly ICustomerRepository _customerRepository;
        private readonly IUnitOfWork _unitOfWork;

        public AuthController(ICustomerRepository customerRepository, IUnitOfWork unitOfWork)
        {
            _customerRepository = customerRepository;
            _unitOfWork = unitOfWork;
        }

        // Display sign in page with a button for authenticating using Google
        // Return View()
        public IActionResult Index(string errorMessage, string returnUrl = "/")
        {
            return View(new AuthHomeModel
            {
                ErrorMessage = errorMessage,
                ReturnUrl = returnUrl
            });
        }

        // This action is called when sign in with google button is clicked
        // Return Challenge result with google authentication scheme
        public IActionResult SignInWithGoogle(string returnUrl)
        {
            var props = new AuthenticationProperties
            {
                RedirectUri = Url.Action("SignInWithGoogleCallback"),
                Items = { { "returnUrl", returnUrl } }
            };
            return Challenge(props, GoogleDefaults.AuthenticationScheme);
        }

        // This action is called when Google finishes authenticating user
        // Check if the user is already in database, if not add user to database
        // Redirect to returnUrl item param on completion
        public async Task<IActionResult> SignInWithGoogleCallback()
        {
            var result = await HttpContext.AuthenticateAsync(ExternalAuthenticationDefaults.AuthenticationScheme);

            var externalClaims = result.Principal.Claims.ToList();

            var subjectID = externalClaims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;

            Customer customer = await _customerRepository.FindAsync(subjectID);

            if (customer == null)
            {
                customer = new Customer
                {
                    ID = subjectID,
                    Name = externalClaims.FirstOrDefault(x => x.Type == ClaimTypes.Name)?.Value,
                    Email = externalClaims.FirstOrDefault(x => x.Type == ClaimTypes.Email)?.Value,
                    ImgUrl = externalClaims.FirstOrDefault(x => x.Type == "image")?.Value,
                    Points = 0,
                    LastSignIn = DateTime.Now
                };

                await _customerRepository.AddAsync(customer);
                await _unitOfWork.CommitAsync();
            }

            await HttpContext.SignOutAsync(ExternalAuthenticationDefaults.AuthenticationScheme);

            // Customer is banned
            if (customer.IsSoftDeleted)
            {
                return RedirectToAction("Index", new { errorMessage = "This account was banned, please contact support for more information" });
            }
            var claims = new List<Claim> {
                new Claim(ClaimTypes.NameIdentifier, customer.ID),
                new Claim(ClaimTypes.Name, customer.Name),
                new Claim(ClaimTypes.Email, customer.Email),
                new Claim("ImgUrl", customer.ImgUrl)
            };

            var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var principal = new ClaimsPrincipal(identity);

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

            return LocalRedirect(result.Properties.Items["returnUrl"]);
        }

        public new async Task<IActionResult> SignOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return LocalRedirect("/");
        }
    }
}

Controllers/BlogController.cs
using Client.Models;
using Core.Entities;
using Core.Helpers;
using Core.Interfaces;
using Core.Services;
using Core.Value_Objects;
using Infrastructure.InterfaceImpls;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class BlogController : BaseController
    {
        private static readonly int _pageSize = 10;
        private readonly BlogFilterService _filterService;
        private readonly BlogRecommendationService _recommendationService;
        private readonly IPostRepository<Post, Employee> _postRepository;
        private readonly IUnitOfWork _unitOfWork;

        public BlogController(IPostRepository<Post, Employee> postRepository, BlogFilterService filterService, BlogRecommendationService recommendationService, IUnitOfWork unitOfWork)
        {
            _postRepository = postRepository;
            _filterService = filterService;
            _recommendationService = recommendationService;
            _unitOfWork = unitOfWork;
        }

        // Display list of blog posts
        // Parameter pageNumber specify which set of tours to display according to pageSize
        // Returns View(postList)
        public IActionResult Index(BlogFilterParams filterParams, int pageNumber = 1)
        {
            IEnumerable<IPost<Employee>> posts = _postRepository.Queryable
                .Include(p => p.Owner)
                .Include(p => p.Comments)
               .Select(p => (IPost<Employee>)p);

            var filteredPosts = _filterService.ApplyFilter(posts, filterParams);

            return View(new BlogListModel
            {
                Posts = PaginatedList<IPost<Employee>>.Create(filteredPosts.AsQueryable(), pageNumber, _pageSize),
                FilterParams = filterParams
            });
        }

        // Display detail of a blog post
        // Parameter id represent the id of the post, it is null when client does not provide id or given id cannot be converted to int
        // Return Notfound() when invalid id or no post with id is found, View(post) otherwise
        public async Task<IActionResult> Detail(int id)
        {
            var post = await _postRepository.Queryable
                .Include(p => p.Owner)
                .Include(p => p.Comments)
                .ThenInclude(cmt => cmt.Owner)
                .FirstOrDefaultAsync(p => p.ID == id);

            if (post == null)
            {
                return NotFound();
            }

            IEnumerable<IPost<Employee>> recommendCandidates = _postRepository.Queryable
                .Include(p => p.Owner)
                .Include(p => p.Comments)
               .Select(p => (IPost<Employee>)p);

            return View(new PostDetailModel
            {
                Post = post,
                Recommendations = _recommendationService.GetRecommendations(recommendCandidates, post)
            });
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddComment(Comment comment)
        {
            var post = await _postRepository.FindAsync(comment.PostID);

            if (post == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                comment.OwnerID = UserID;
                comment.LastUpdated = DateTime.Now;
                await _postRepository.AddComment(comment);
                await _unitOfWork.CommitAsync();
            }

            return RedirectToAction(nameof(Detail), new { id = post.ID });
        }
    }
}

Controllers/CustomerController.cs
using Client.Models;
using Core.Entities;
using Core.Helpers;
using Core.Interfaces;
using Infrastructure.InterfaceImpls;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class CustomerController : BaseController
    {
        private static readonly int _pageSize = 10;
        private readonly IBookingRepository _bookingRepository;
        private readonly ITourReviewRepository _tourReviewRepository;
        private readonly IPostRepository<Post, Employee> _postRepository;
        private readonly ICustomerRepository _customerRepository;
        private readonly IUnitOfWork _unitOfWork;

        public CustomerController(IUnitOfWork unitOfWork, ICustomerRepository customerRepository, IBookingRepository bookingRepository, ITourReviewRepository tourReviewRepository, IPostRepository<Post, Employee> postRepository)
        {
            _unitOfWork = unitOfWork;
            _bookingRepository = bookingRepository;
            _postRepository = postRepository;
            _customerRepository = customerRepository;
            _tourReviewRepository = tourReviewRepository;
        }

        // Display user main screen, including user details and list of upcoming trips
        // View(userHomeViewModel)
        public async Task<IActionResult> Index()
        {
            IEnumerable<Booking> bookingList = _bookingRepository.Queryable.Include(bk => bk.Trip).ThenInclude(tr => tr.Tour);

            Customer customer = await _customerRepository.FindAsync(UserID);

            return View(new CustomerHomeModel
            {
                Bookings = bookingList,
                Customer = customer
            });
        }

        [HttpPost]
        public async Task<IActionResult> Update(Customer customer)
        {

            if (!ModelState.IsValid)
            {
                return View(
                new CustomerHomeModel
                {
                    Bookings = _bookingRepository.Queryable.Include(bk => bk.Trip).ThenInclude(tr => tr.Tour),
                    Customer = customer
                });
            }

            var existingUser = await _customerRepository.FindAsync(UserID);

            existingUser.Name = customer.Name;
            existingUser.PhoneNumber = customer.PhoneNumber;
            existingUser.Address = customer.Address;
            existingUser.DOB = customer.DOB;

            await _customerRepository.UpdateAsync(existingUser);
            await _unitOfWork.CommitAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Points(int pageNumber = 1)
        {
            Customer customer = await _customerRepository.FindAsync(UserID);
            IEnumerable<PointLog> logs = _customerRepository.GetPointsLogs(customer);

            return View(new CustomerPointsModel
            {
                Points = customer.Points,
                PointLogs = PaginatedList<PointLog>.Create(logs.AsQueryable(), pageNumber, _pageSize)
            });
        }

        [HttpPost]
        public async Task<IActionResult> Review(int bookingID, TourReview tourReview, string returnUrl)
        {
            returnUrl ??= Url.Action(nameof(Index));

            var booking = await _bookingRepository.Queryable
                .Include(bk => bk.Trip)
                .Include(bk => bk.Review)
                .FirstOrDefaultAsync(bk => bk.ID == bookingID);

            if (booking == null)
            {
                return NotFound();
            }


            if (!booking.CanBeReviewed(DateTime.Now))
            {
                return Forbid();
            }

            tourReview.BookingID = booking.ID;
            tourReview.LastUpdated = DateTime.Now;

            await _bookingRepository.UpdateAsync(booking);
            await _tourReviewRepository.AddAsync(tourReview);
            await _unitOfWork.CommitAsync();

            return LocalRedirect(returnUrl);
        }
    }
}

Controllers/TourController.cs
using Core.Interfaces;
using Client.Models;
using Core.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace Client.Controllers
{
    public class TourController : BaseController
    {
        private static readonly int _pageSize = 10;
        private readonly ITourRepository _tourRepository;
        private readonly ICustomerRepository _customerRepository;
        private readonly IUnitOfWork _unitOfWork;

        public TourController(ITourRepository tourRepository, ICustomerRepository customerRepository, IUnitOfWork unitOfWork)
        {
            _tourRepository = tourRepository;
            _customerRepository = customerRepository;
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index(int pageNumber = 1)
        {

            IEnumerable<Tour> tours = _tourRepository.Queryable.Where(Tour => Tour.IsOpen).AsEnumerable();
            return View(new TourListModel
            {
                Tours = PaginatedList<Tour>.Create(tours.AsQueryable(), pageNumber, _pageSize)
            });
        }

        [Authorize]
        public async Task<IActionResult> ToggleFollow(int id)
        {
            var tour = await _tourRepository.FindAsync(id);

            if (tour == null)
            {
                return NotFound();
            }

            var customer = await _customerRepository.Queryable
                .Include(cus => cus.TourFollowings)
                .FirstOrDefaultAsync(cus => cus.ID == UserID);

            if (customer.IsFollowing(tour))
            {
                _customerRepository.UnFollow(customer, tour);
            }
            else
            {
                _customerRepository.Follow(customer, tour);
            }

            await _unitOfWork.CommitAsync();

            return RedirectToAction("Detail", "Trip", new { id = id });
        }
    }
}

Views/Shared/_DataTable.cshtml
@*
    Partial for enabling jquery dataTable for a table
    Model is a string representing the id of the target tables separated by ','
    Add the class 'no-ordering' to a 'th' tag in the 'theader' to disable ordering the corresponding column
*@

@model string


<link href="~/lib/data-tables/css/dataTables.bootstrap5.min.css" rel="stylesheet" />
<script src="~/lib/data-tables/js/jquery.dataTables.min.js"></script>
<script src="~/lib/data-tables/js/dataTables.bootstrap5.min.js"></script>

<style>
    .dataTables_filter {
        padding-top: .25rem;
        padding-right: .25rem;
    }

    .dt-bootstrap5 table {
        padding-bottom: 1rem;
    }
</style>

<input type="hidden" id="tblID" value="@Model" />

<script>
    let tblIDs = $('#tblID').val();

    $(document).ready(function () {
        for (let tblID of tblIDs.split(/,\s*/)) {
            let orderingDisabled = [];
            for (const [i, th] of Array.from(document.getElementById(tblID).getElementsByTagName("thead")[0].getElementsByTagName("tr")[0].getElementsByTagName("th")).entries()) {
                if (th.classList.contains("no-ordering")) {
                    orderingDisabled.push(i);
                }
            }
            $(`#${tblID}`).DataTable({
                columnDefs: [
                    { orderable: false, targets: orderingDisabled }
                ]
            });
        }
    });
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ETourClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap-select/css/bootstrap-select.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/snackbar/snackbar.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/snackbar/snackbar.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap-select/js/bootstrap-select.min.js" asp-append-version="true"></script>
</head>
<body style="margin-bottom: 0">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm fixed-top navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo.svg" height="25" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="ml-auto navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav justify-content-end flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Tour" asp-action="Index">Tours</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Trip" asp-action="Index">Trips</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Blog" asp-action="Index">Blog</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @User.Identity.Name
                                </a>
                                <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                                    <a class="nav-link" asp-area="" asp-controller="Customer" asp-action="Index">Profile</a>
                                    <a class="nav-link" asp-area="" asp-controller="Booking" asp-action="History">Bookings</a>
                                    <a class="nav-link" asp-area="" asp-controller="Question" asp-action="Index">Questions</a>
                                    <a class="nav-link" asp-area="" asp-controller="Customer" asp-action="Points">Points</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="nav-link" asp-area="" asp-controller="Auth" asp-action="SignOut">Sign out</a>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Auth" asp-action="Index">Sign in</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="position-relative">
        @RenderBody()
    </main>
    <!-- Footer -->
    <footer class="bg-dark text-center text-white">
        <!-- Grid container -->
        <div class="container p-4">

            <!-- Section: Social media -->
            <section class="mb-4">
                <!-- Facebook -->
                <a class="btn btn-primary btn-floating m-1" style="background-color: #3b5998" href="#!" role="button"><i class="fab fa-facebook-f"></i></a>

                <!-- Twitter -->
                <a class="btn btn-primary btn-floating m-1" style="background-color: #55acee" href="#!" role="button"><i class="fab fa-twitter"></i></a>

                <!-- Google -->
                <a class="btn btn-primary btn-floating m-1" style="background-color: #dd4b39" href="#!" role="button"><i class="fab fa-google"></i></a>

                <!-- Instagram -->
                <a class="btn btn-primary btn-floating m-1" style="background-color: #ac2bac" href="#!" role="button"><i class="fab fa-instagram"></i></a>

                <!-- Linkedin -->
                <a class="btn btn-primary btn-floating m-1" style="background-color: #0082ca" href="#!" role="button"><i class="fab fa-linkedin-in"></i></a>
                <!-- Github -->
                <a class="btn btn-primary btn-floating m-1" style="background-color: #333333" href="#!" role="button"><i class="fab fa-github"></i></a>
            </section>
            <!-- Section: Social media -->
            <!-- Section: Form -->
            <section class="">
                <form action="">
                    <!--Grid row-->
                    <div class="row d-flex justify-content-center">
                        <!--Grid column-->
                        <div class="col-auto">
                            <p class="pt-2">
                                <strong>Sign up for our newsletter</strong>
                            </p>
                        </div>
                        <!--Grid column-->
                        <!--Grid column-->
                        <div class="col-md-5 col-12">
                            <!-- Email input -->
                            <div class="form-outline form-white mb-4">
                                <input type="email" id="form5Example2" class="form-control" />
                                <label class="form-label" for="form5Example2">Email address</label>
                            </div>
                        </div>
                        <!--Grid column-->
                        <!--Grid column-->
                        <div class="col-auto">

                            <!-- Submit button -->
                            <button type="submit" class="btn btn-outline-light mb-4">
                                Subscribe
                            </button>
                        </div>
                        <!--Grid column-->
                    </div>
                    <!--Grid row-->
                </form>
            </section>
            <!-- Section: Form -->
            <!-- Section: Text -->
            <section class="mb-4">
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt
                    distinctio earum repellat quaerat voluptatibus placeat nam,
                    commodi optio pariatur est quia magnam eum harum corrupti dicta,
                    aliquam sequi voluptate quas.
                </p>
            </section>
            <!-- Section: Text -->
            <!-- Section: Links -->
            <section class="">
                <!--Grid row-->
                <div class="row">
                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase">Links</h5>

                        <ul class="list-unstyled mb-0">
                            <li>
                                <a href="#!" class="text-white">Link 1</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 2</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 3</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 4</a>
                            </li>
                        </ul>
                    </div>
                    <!--Grid column-->
                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase">Links</h5>

                        <ul class="list-unstyled mb-0">
                            <li>
                                <a href="#!" class="text-white">Link 1</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 2</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 3</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 4</a>
                            </li>
                        </ul>
                    </div>
                    <!--Grid column-->
                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase">Links</h5>

                        <ul class="list-unstyled mb-0">
                            <li>
                                <a href="#!" class="text-white">Link 1</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 2</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 3</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 4</a>
                            </li>
                        </ul>
                    </div>
                    <!--Grid column-->
                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase">Links</h5>

                        <ul class="list-unstyled mb-0">
                            <li>
                                <a href="#!" class="text-white">Link 1</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 2</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 3</a>
                            </li>
                            <li>
                                <a href="#!" class="text-white">Link 4</a>
                            </li>
                        </ul>
                    </div>
                    <!--Grid column-->
                </div>
                <!--Grid row-->
            </section>
            <!-- Section: Links -->

        </div>
        <!-- Grid container -->
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
            © 2020 Copyright:
            <a class="text-white" href="https://mdbootstrap.com/">Toure Inc</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
    <!-- Back to top button -->
    <a id="back-to-top" href="#" class="btn btn-secondary btn-lg back-to-top" role="button"><i class="fas fa-chevron-up"></i></a>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}


Views/Shared/_Pagination.cshtml
@model PaginationInfo

@{
    int start = !Model.HasPreviousPage ? 1 : !Model.HasNextPage ? Math.Max(Model.TotalPages - 3, 1) : Model.PageIndex - 1;
}

<nav aria-label="Trip Pagination">
    <ul class="pagination justify-content-end">
        <li class="page-item @(!Model.HasPreviousPage? "disabled": "")">
            <a style="cursor: pointer" onclick="paginate(1)" class="page-link text-@(!Model.HasPreviousPage? "secondary": "primary")">Previous</a>
        </li>
        @for (int i = start; i <= Math.Min(start + 3, Model.TotalPages); i++)
        {
            <li class="page-item @(i == Model.PageIndex ? "active": "")"><a style="cursor: pointer" onclick="@(i == Model.PageIndex? "": $"paginate({i})")" class="page-link text-@(i == Model.PageIndex? "white": "primary")">@i</a></li>
        }
        <li class="page-item @(!Model.HasNextPage? "disabled": "")">
            <a style="cursor: pointer" onclick="paginate(@Model.TotalPages)" class="page-link text-@(!Model.HasNextPage? "secondary": "primary")">Next</a>
        </li>
    </ul>
</nav>

<script>
    function paginate(pageNumber) {
        let searchParams = new URLSearchParams(window.location.search);
        searchParams.set("pageNumber", pageNumber);
        window.location.href = `${window.location.pathname}?${searchParams}`;
    }
</script>