Models/Customer/CustomerHomeModel.cs
using Core.Entities;
using System.Collections.Generic;

namespace Client.Models
{
    public class CustomerHomeModel
    {
        public Customer Customer { get; set; }
        public IEnumerable<Booking> Bookings { get; set; }
        public Trip Trips { get; set; }
        public IEnumerable<Booking> UpcomingTrips { get; set; }

    }
}

Models/Customer/CustomerPointsModel.cs
using Core.Entities;
using Core.Helpers;

namespace Client.Models
{
    public class CustomerPointsModel
    {
        public int Points { get; set; }
        public PaginatedList<PointLog> PointLogs { get; set; }
    }
}

Controllers/BookingController.cs
using Client.Models;
using Core.Entities;
using Core.Interfaces;
using Core.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    [Authorize]
    public class BookingController : BaseController
    {
        private readonly IZaloPayService _zaloPayService;
        private readonly IMomoPaymentService _momoPaymentService;
        private readonly QRCodeService _QRCodeService;
        private readonly ITripRepository _tripRepository;
        private readonly ICustomerRepository _customerRepository;
        private readonly IBookingRepository _bookingRepository;
        private readonly IInvoiceRepository _invoiceRepository;
        private readonly IUnitOfWork _unitOfWork;
        // Display list of the tickets user had added to cart but not yet paid for
        // Return View(bookingList)
        public BookingController(IUnitOfWork unitOfWork, IBookingRepository bookingrepository, ICustomerRepository customerRepository, ITripRepository tripRepository, IInvoiceRepository invoiceRepository, IZaloPayService zaloPayService, IMomoPaymentService momoPaymentService, QRCodeService QRCodeService)
        {
            _bookingRepository = bookingrepository;
            _customerRepository = customerRepository;
            _tripRepository = tripRepository;
            _unitOfWork = unitOfWork;
            _zaloPayService = zaloPayService;
            _invoiceRepository = invoiceRepository;
            _momoPaymentService = momoPaymentService;
            _QRCodeService = QRCodeService;
        }
        public IActionResult Index()
        {
            IEnumerable<Booking> bookingList = _bookingRepository.Queryable.Include(bk => bk.Trip).ThenInclude(tr => tr.Tour);

            return View(bookingList);
        }

        // Display a form for user to enter essential information to add a new booking to cart
        // Parameter tripId represents the id of the trip user want to book, it is null if not provided or cannot be converted to int
        // Return NotFound() if tripId is null or no trip with tripId is found, View(bookingModel) otherwise
        public async Task<IActionResult> New(int tripID)
        {
            var customer = await _customerRepository.FindAsync(UserID);

            var trip = await _tripRepository.Queryable
                .Include(tr => tr.Tour)
                .Include(tr => tr.TripDiscounts)
                .ThenInclude(td => td.Discount)
                .Include(tr => tr.Bookings)
                .FirstOrDefaultAsync(tr => tr.ID == tripID);

            var applicablePoints = new Booking { Total = trip.GetSalePriceFor(CustomerInfo.CustomerAgeGroup.Adult) }.GetApplicablePoints(customer.Points);

            if (trip == null || !trip.CanBook(DateTime.Now))
            {
                return NotFound();
            }

            return View(new BookingFormModel
            {
                Trip = trip,
                Customer = customer,
                Total = trip.GetSalePriceFor(CustomerInfo.CustomerAgeGroup.Adult),
                ApplyPoints = false,
                ApplyAmount = applicablePoints
            });
        }

        // This action is called when user submit booking form to add new booking to cart
        // Parameter tripId represents the id of the trip user want to book, it is null if not provided or cannot be converted to int
        // Parameter model represent the model bound values that supports form validation
        // Return NotFound() if tripId is null or no trip with tripId is found, View(bookingModel) otherwise
        [HttpPost]
        public async Task<IActionResult> New(Booking booking, string[] customerNames, CustomerInfo.CustomerSex[] customerSexes, DateTime[] customerDobs, bool applyPoints)
        {
            var trip = await _tripRepository.Queryable
                            .Include(tr => tr.Tour)
                            .Include(tr => tr.TripDiscounts)
                            .ThenInclude(td => td.Discount)
                            .Include(tr => tr.Bookings)
                            .FirstOrDefaultAsync(tr => tr.ID == booking.TripID);
            var customer = await _customerRepository.FindAsync(UserID);

            if (trip == null || !trip.CanBook(DateTime.Now))
            {
                return NotFound();
            }

            var ageGroups = customerDobs.Select(dob => CustomerInfo.AgeGroupFor(dob)).ToArray();
            var salePrices = trip.GetSalePricesFor(ageGroups);
            booking.Total = salePrices.Sum();
            var applyAmount = 0;

            if (applyPoints)
            {
                applyAmount = await GetApplicablePoints(booking);
                booking.Total -= applyAmount;
            }

            if (booking.TicketCount > trip.Vacancies)
            {
                ModelState.AddModelError(string.Empty, "There was not enough vacancies for your booking request");
            }

            if (customer.Points < applyAmount)
            {
                ModelState.AddModelError(string.Empty, "You points amount changed unexpectedly during the booking");
            }

            if (!ModelState.IsValid)
            {
                return View(new BookingFormModel
                {
                    Customer = customer,
                    Booking = booking,
                    CustomerNames = customerNames,
                    CustomerSexes = customerSexes,
                    CustomerDobs = customerDobs,
                    CustomerAgeGroups = ageGroups,
                    SalePrices = salePrices,
                    Trip = trip,
                    Total = booking.Total,
                });
            }

            booking.OwnerID = UserID;

            for (int i = 0; i < customerNames.Length; i++)
            {
                var ageGroup = CustomerInfo.AgeGroupFor(customerDobs[i]);

                booking.CustomerInfos.Add(new CustomerInfo
                {
                    Name = customerNames[i],
                    Sex = customerSexes[i],
                    DOB = customerDobs[i],
                    AgeGroup = ageGroup
                });
            }

            booking.Status = Booking.BookingStatus.Awaiting_Deposit;
            booking.PaymentDeadline = DateTime.Now.AddDays(2);
            booking.TicketCount = booking.CustomerInfos.Count;
            booking.PointsApplied = applyAmount;
            booking.LastUpdated = DateTime.Now;
            booking.SetDeposit(trip.Deposit);

            booking.ChargePoints(customer);

            await _customerRepository.UpdateAsync(customer);
            foreach (var pointLog in booking.PointLogs)
            {
                _customerRepository.AddPointLog(pointLog);
            }
            await _bookingRepository.AddAsync(booking);
            await _unitOfWork.CommitAsync();

            return RedirectToAction("Detail", new { id = booking.ID });
        }



        public async Task<IActionResult> Detail(int id)
        {
            var booking = await _bookingRepository.Queryable
                .Include(bk => bk.Trip)
                .ThenInclude(tr => tr.Tour)
                .Include(bk => bk.CustomerInfos)
                .Include(bk => bk.Owner)
                .FirstOrDefaultAsync(bk => bk.ID == id);

            if (booking == null)
            {
                return NotFound();
            }

            return booking.Status switch
            {
                Booking.BookingStatus.Awaiting_Deposit => View("Views/Booking/Deposit.cshtml", booking),

                Booking.BookingStatus.Processing => View("Views/Booking/Processing.cshtml", booking),
                Booking.BookingStatus.Awaiting_Payment => View("Views/Booking/Payment.cshtml", booking),
                Booking.BookingStatus.Completed => View("Views/Booking/Completed.cshtml", booking),
                Booking.BookingStatus.Canceled => View("Views/Booking/Canceled.cshtml", booking),
                _ => throw new InvalidOperationException(),

            };
        }

        [HttpPost]
        public async Task<IActionResult> GenerateDepositQRCode(int id, Invoice.PaymentMethod method)
        {
            var booking = await _bookingRepository.Queryable
                            .Include(bk => bk.Trip)
                            .ThenInclude(tr => tr.Tour)
                            .Include(bk => bk.Owner)
                            .FirstOrDefaultAsync(bk => bk.ID == id);

            if (booking == null || booking.Status != Booking.BookingStatus.Awaiting_Deposit && booking.Status != Booking.BookingStatus.Awaiting_Payment)
            {
                return NotFound();
            }

            string paymentUrl = "";
            string viewName = "";

            switch (method)
            {
                case Invoice.PaymentMethod.Zalo_Pay:
                    paymentUrl = await _zaloPayService.CreateOrderAsync(booking, (long)booking.Deposit, $"Toure: Deposit for tour {booking.Trip.Tour.Title}");
                    viewName = "ZaloPay";
                    break;
                case Invoice.PaymentMethod.Momo:
                    paymentUrl = await _momoPaymentService.CreateOrderAsync(booking, (long)booking.Deposit, $"Toure: Deposit for tour {booking.Trip.Tour.Title}");
                    return Redirect(paymentUrl);
                case Invoice.PaymentMethod.GPay:
                    break;
                default:
                    break;
            }

            
            return View(viewName, new QRPaymentModel
            {

Controllers/PointController.cs
using Client.Models;
using Core.Entities;
using Core.Helpers;
using Core.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace Client.Controllers
{
    public class PointController : BaseController
    {
        private static readonly int _pageSize = 10;
        private readonly ICustomerRepository _customerRepository;
        public PointController(ICustomerRepository customerRepository)
        {
            _customerRepository = customerRepository;
        }
        public async Task<IActionResult> Index(int pageNumber = 1)
        {
            Customer customer = await _customerRepository.FindAsync(UserID);
            IEnumerable<PointLog> logs = _customerRepository.GetPointsLogs(customer);
            
            return View(new CustomerPointsModel { 
                Points = customer.Points,
                PointLogs = PaginatedList<PointLog>.Create(logs.AsQueryable(), pageNumber, _pageSize)
            });
        }
    }
}

Controllers/TripController.cs
using Client.Models;
using Core.Entities;
using Core.Helpers;
using Core.Interfaces;
using Core.Services;
using Core.Value_Objects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class TripController : BaseController
    {
        private static readonly int _pageSize = 10;

        private readonly ITripRepository _tripRepository;
        private readonly ITourRepository _tourRepository;
        private readonly ITourReviewRepository _tourReviewRepository;
        private readonly ICustomerRepository _customerRepository;
        private readonly TripFilterService _tripFilterService;
        private readonly TripRecommendationService _recommendationService;

        public TripController(ITripRepository tripRepository, ITourRepository tourRepository, ICustomerRepository customerRepository, ITourReviewRepository tourReviewRepository, TripFilterService tripFilterService, TripRecommendationService recommendationService)
        {
            _tripRepository = tripRepository;
            _tourRepository = tourRepository;
            _tourReviewRepository = tourReviewRepository;
            _customerRepository = customerRepository;
            _tripFilterService = tripFilterService;
            _recommendationService = recommendationService;
        }

        // Display list of trips
        // Parameter filterParams contains info about trip filters (price, starting time, end time, tour)
        // Parameter pageNumber specify which set of tours to display according to pageSize
        // Returns View(tourList)

        public IActionResult Index(TripFilterParams filterParams, int pageNumber = 1)
        {
            var trips = _tripRepository.Queryable
                .Where(tr => tr.IsOpen)
                .Include(tr => tr.Tour)
                .Include(tr => tr.TripDiscounts)
                .ThenInclude(td => td.Discount)
                .Include(tr => tr.Bookings)
                .ThenInclude(bk => bk.Review)
                .AsEnumerable();

            trips = trips.Select(tr =>
            {
                tr.Tour.ReviewSummary = TourReviewSummary.FromReviews(_tourReviewRepository.GetReviewsForTour(tr.Tour));
                return tr;
            });

            var filteredTrips = _tripFilterService.ApplyFilter(trips, filterParams);

            var tours = _tourRepository.Queryable.Where(tour => tour.IsOpen).AsEnumerable();

            var paginatedTrips = PaginatedList<Trip>.Create(filteredTrips.AsQueryable(), pageNumber, _pageSize);

            return View(new TripListModel
            {
                Trips = paginatedTrips,
                Tours = tours,
            });
        }

        // Display detail of a trip, including book button to book a ticket (add to cart)
        // Parameter id represent the id of the trip, it is null when client does not provide id or given id cannot be converted to int
        // Return Notfound() when invalid id or no trip with id is found, View(tripDetails) otherwise
        public async Task<IActionResult> Detail(int id)
        {
            var trip = await _tripRepository.Queryable
                .Include(tr => tr.Tour)
                .Include(tr => tr.Itineraries)
                .Include(tr => tr.TripDiscounts)
                .ThenInclude(tr => tr.Discount)
                .Include(tr => tr.Bookings)
                .ThenInclude(bk => bk.Review)
                .FirstOrDefaultAsync(tr => tr.ID == id);

            trip.Tour.ReviewSummary = TourReviewSummary.FromReviews(_tourReviewRepository.GetReviewsForTour(trip.Tour));

            if (trip == null || !trip.IsOpen)
            {
                return NotFound();
            }

            var customer = await _customerRepository.Queryable
                .Include(cus => cus.Bookings)
                .ThenInclude(bk => bk.Trip)
                .FirstOrDefaultAsync(cus => cus.ID == UserID);

            var recommendCandidates = _tripRepository.Queryable
                .Where(tr => tr.IsOpen)
                .Include(tr => tr.Tour)
                .Include(tr => tr.TripDiscounts)
                .ThenInclude(td => td.Discount)
                .Include(tr => tr.Bookings);

            var reviews = _tourReviewRepository.GetReviewsForTour(trip.Tour);

            return View(new TripDetailModel
            {
                Trip = trip,
                IsTourFollowed = await CheckFollowing(trip.TourID),
                Reviews = reviews,
                Recommendations = _recommendationService.GetRecommendations(recommendCandidates, trip),
            });
        }

        private async Task<bool> CheckFollowing(int tourID)
        {
            // User is not logged in
            if (UserID == null)
            {
                return false;
            }

            var customer = await _customerRepository.Queryable
                .Include(cus => cus.TourFollowings)
                .FirstOrDefaultAsync(cus => cus.ID == UserID);

            return customer.TourFollowings.Any(tf => tf.TourID == tourID);
        }
    }
}

Views/Customer/Index.cshtml
@model Client.Models.CustomerHomeModel
@{
    ViewData["Title"] = "User Info";
}

<div class="container my-5">
    <div class="row justify-content-between">
        <div class="col-md-4">
            <form asp-action="Update" method="post">
                <div class="form-group row justify-content-center">
                    <img class="img-fluid w-50 rounded" src="@Model.Customer.ImgUrl">
                </div>
                <div class="form-group ">
                    <label asp-for="Customer.Name"></label>
                    <input class="form-control" asp-for="Customer.Name">
                    <span asp-validation-for="Customer.Name"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Customer.PhoneNumber"></label>
                    <input class="form-control" asp-for="Customer.PhoneNumber">
                    <span asp-validation-for="Customer.PhoneNumber"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Customer.Address"></label>
                    <input class="form-control" asp-for="Customer.Address">
                </div>
                <div class="form-group">
                    <label asp-for="Customer.Email"></label>
                    <input class="form-control" asp-for="Customer.Email" disabled>
                    <span asp-validation-for="Customer.Email"></span>
                </div>
                <div class="form-group d-flex">
                    <div>
                        <label asp-for="Customer.Points"></label>
                        <input class="form-control" asp-for="Customer.Points" disabled>
                    </div>
                    <div class="ml-2">
                        <label asp-for="Customer.DOB">Date of birth</label>
                        <input class="form-control" asp-for="Customer.DOB" />
                        <span asp-validation-for="Customer.DOB"></span>
                    </div>
                </div>
                <hr class="my-4">
                <button type="submit" class="btn btn-primary">
                    Update Information
                </button>
            </form>
        </div>


        <div class="col-md-8 col-offset-md-1 mt-5 mt-md-0">
            <div class="card">
                <div class="card-header">
                    <h3 class="mt-md-0 font-weight-normal">Upcoming trips</h3>
                </div>
                <div class="card-body">
                    @foreach (var b in Model.Bookings)
                    {<div class="row mb-4">
                        <div class="col-md-5 col-xl-4">
                            <img class="img-fluid w-100 h-100 rounded" style="object-fit: cover" src="@b.Trip.Tour.ImageUrls[0]" alt="Sample">
                        </div>


                        <div class="col-md-7 col-xl-8">
                            <div>
                                <div class="row">
                                    <div class="col-8">
                                        <h5>Tour @b.Trip.Tour.StartPlace - @b.Trip.Tour.Destination </h5>
                                        <p class="mb-3 text-muted text-uppercase small">Status: <span class="@b.Status.Badge()">@b.Status.ToCustomString()</span></p>
                                        <p class="mb-2 text-muted text-uppercase small">
                                            Time frame: <span class="bg-light-primary text-center">@b.Trip.StartTime.Day.@b.Trip.StartTime.Month.@b.Trip.StartTime.Year - @b.Trip.EndTime.Day.@b.Trip.EndTime.Month.@b.Trip.EndTime.Year</span>
                                        </p>
                                        <p class="mb-2 text-muted text-uppercase small">Duration: @(b.Trip.EndTime.Day-b.Trip.StartTime.Day) days</p>
                                    </div>
                                    <div class="col-4">
                                        <p class="text-right">Quantity: @(b.TicketCount)</p>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <a asp-controller="Booking" asp-action="Detail" asp-route-id="@b.ID" class="btn btn-outline-primary">Detail</a>
                                        <button disabled="@(!b.CanCancel(DateTime.Now))" onclick="showCancelForm(this, this.getAttribute('data-id'))" data-id="@b.ID" class="btn btn-outline-danger"><span data-feather="trash" />Cancel</button>
                                    </div>
                                    <p class="mb-0 text-right text-danger">Total: @b.Total.ToCurrencyString()</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    }
                    @if (!Model.Bookings.Any())
                    {
                    <div class="w-100 d-flex justify-content-center my-5">
                        <img class="w-50" src="~/images/empty_cart.svg" alt="empty cart illustration" />
                    </div>
                    <div class="w-100 d-flex justify-content-center">
                        <p class="w-50 text-muted text-center">Looks like you have no upcoming trips, <a asp-action="Index" asp-controller="Trip" class="text-primary">go here</a> to book your next trip!</p>
                    </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="cancel-booking-container" tabindex="-1" role="dialog" aria-labelledby="cancelationModalLabel" aria-hidden="true"></div>

@section Scripts {
    <script src="~/js/booking.js"></script>
}

Views/Customer/Points.cshtml
@model CustomerPointsModel
@{
    ViewData["Title"] = "Pointlog";
}

<div class="container py-5">
    <div class="d-flex justify-content-between mb-3">
        <h3>Point Activities</h3>
        <p style="font-size: 1.15rem" class="bg-light p-2 font-weight-light text-info">Your Points: @Model.Points</p>
    </div>
    @if (Model.PointLogs.Count() > 0)
    {
        <ul class="list-group">
            @foreach (var p in Model.PointLogs)
            {
                <li class="list-group-item shadow-hover mb-3">
                    <h4 class="text-@(p.Amount > 0? "success": "danger")">
                        @if (p.Amount > 0)
                        {<span>+</span>}@p.Amount Points
                    </h4>
                    <p><b> @p.Trigger</b></p>
                    <p>@p.Description</p>
                    <p><small>@p.LastUpdated.Date</small></p>
                </li>
            }
        </ul>
        <partial name="_Pagination" model="Model.PointLogs.PaginationInfo" />
    }
    else
    {
        <p class="text-muted text-center mt-5">No have no point activity</p>
    }

</div>